apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: # manifests generated during bootstrap
  - install.yaml
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: registry
      namespace: ocm-system
    spec:
      template:
        spec:
          containers:
            - name: registry
              env:
                - name: REGISTRY_HTTP_TLS_CERTIFICATE
                  value: "/certs/cert.pem"
                - name: REGISTRY_HTTP_TLS_KEY
                  value: "/certs/key.pem"
                - name: REGISTRY_HTTP_TLS_CLIENTCAS_0
                  value: "/certs/ca.pem"
              volumeMounts:
                - mountPath: "/certs"
                  name: "ocm-registry-tls-certs"
          volumes:
            - name: "ocm-registry-tls-certs"
              secret:
                secretName: ocm-registry-tls-certs
                items:
                  - key: "tls.crt"
                    path: "cert.pem"
                  - key: "tls.key"
                    path: "key.pem"
                  - key: "ca.crt"
                    path: "ca.pem"
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ocm-controller
      namespace: ocm-system
    spec:
      template:
        spec:
          containers:
            - name: manager
              volumeMounts:
                - mountPath: "/etc/ssl/certs/registry-root.pem"
                  subPath: "registry-root.pem"
                  name: "certificates"
          volumes:
            - name: "certificates"
              secret:
                secretName: ocm-registry-tls-certs
                items:
                  - key: "ca.crt"
                    path: "registry-root.pem"

