apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: # manifests generated during bootstrap
  - install.yaml
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: git-controller
      namespace: ocm-system
    spec:
      template:
        spec:
          containers:
            - name: manager
              volumeMounts:
                - mountPath: "/etc/ssl/certs/registry-root.pem"
                  subPath: "registry-root.pem"
                  name: "certificates"
          volumes:
            - name: "certificates"
              secret:
                secretName: ocm-registry-tls-certs
                items:
                  - key: "ca.crt"
                    path: "registry-root.pem"
