apiVersion: meta.mpas.ocm.software/v1alpha1
kind: ProductDescription
metadata:
  name: podinfo
spec:
  description: Podinfo
  pipelines:
  - name: podinfo
    targetRoleName: ingress
    source:
      name: manifests
      version: 1.0.0
    localization:
      name: config
      version: 1.0.0
    configuration:
      rules:
        name: config
        version: 1.0.0
    schema:
      name: schema
      version: 1.0.0
  targetRoles:
  - name: ingress
    type: kubernetes
    selector:
      matchLabels:
        target.mpas.ocm.software/ingress-enabled: "true"

